/**
 * Every member upstream's type definitions declare for a card script.
 *
 * Not a list of what Iris provides — `identity.ts` is that, and it holds 31 of
 * these. This is the far larger set a card **may reasonably reach for**, and it
 * exists so that reaching for one Iris has not built produces the right
 * sentence.
 *
 * Without it, `getTavernHelperVersion is not defined` reads as a broken card, and
 * that misattribution is the expensive kind: the report arrives with a suspect
 * already named, so nobody checks the innocent party. It has cost this project
 * twice already — first `waitGlobalInitialized`, then Vue, where a library Iris
 * was supposed to seed went unnamed because no list knew about it. The shape is
 * identical both times: **a checklist can only ever speak about names that are
 * on it**, so anything missing from the list is missing from every report the
 * list can produce.
 *
 * Extracted from the installed Tavern Helper's `@types` declarations rather than
 * written by hand, and pinned by a test that re-extracts them when that corpus
 * is present. A hand-kept list of 171 names would rot silently, and the rot is
 * invisible until a card is handed the wrong diagnosis.
 *
 * Membership here says nothing about whether Iris implements a member — only
 * that a card is entitled to expect it. `identity.ts` answers the other question.
 *
 * @module iris-web/sandbox/upstream-surface
 */

/** Names upstream declares as available to a card script. */
export const UPSTREAM_MEMBERS: readonly string[] = [
  'EjsTemplate',
  'Mvu',
  'SillyTavern',
  'TavernHelper',
  'appendAudioList',
  'appendInexistentScriptButtons',
  'builtin',
  'builtin_prompt_default_order',
  'createCharacter',
  'createChatMessages',
  'createLorebook',
  'createLorebookEntries',
  'createOrReplaceCharacter',
  'createOrReplacePersona',
  'createOrReplacePreset',
  'createOrReplaceWorldbook',
  'createPersona',
  'createPreset',
  'createWorldbook',
  'createWorldbookEntries',
  'default_preset',
  'deleteCharacter',
  'deleteChatMessages',
  'deleteLorebook',
  'deleteLorebookEntries',
  'deletePersona',
  'deletePreset',
  'deleteVariable',
  'deleteWorldbook',
  'deleteWorldbookEntries',
  'errorCatched',
  'eventClearAll',
  'eventClearEvent',
  'eventClearListener',
  'eventEmit',
  'eventEmitAndWait',
  'eventMakeFirst',
  'eventMakeLast',
  'eventOn',
  'eventOnButton',
  'eventOnce',
  'eventRemoveListener',
  'formatAsDisplayedMessage',
  'formatAsTavernRegexedString',
  'generate',
  'generateRaw',
  'getAllEnabledScriptButtons',
  'getAllVariables',
  'getAudioList',
  'getAudioSettings',
  'getButtonEvent',
  'getCharAvatarPath',
  'getCharData',
  'getCharLorebooks',
  'getCharWorldbookNames',
  'getCharacter',
  'getCharacterIds',
  'getCharacterNames',
  'getChatHistoryBrief',
  'getChatHistoryDetail',
  'getChatLorebook',
  'getChatMessages',
  'getChatWorldbookName',
  'getCurrentAudio',
  'getCurrentCharPrimaryLorebook',
  'getCurrentCharacterId',
  'getCurrentCharacterName',
  'getCurrentMessageId',
  'getCurrentPersonaId',
  'getCurrentPersonaName',
  'getExtensionInstallationInfo',
  'getExtensionType',
  'getGlobalWorldbookNames',
  'getIframeName',
  'getLastMessageId',
  'getLoadedPresetName',
  'getLorebookEntries',
  'getLorebookSettings',
  'getLorebooks',
  'getMessageId',
  'getModelList',
  'getOrCreateChatLorebook',
  'getOrCreateChatWorldbook',
  'getPersona',
  'getPersonaAvatarPath',
  'getPersonaIds',
  'getPersonaNames',
  'getPreset',
  'getPresetNames',
  'getProxyPresetNames',
  'getScriptButtons',
  'getScriptId',
  'getScriptInfo',
  'getScriptName',
  'getScriptTrees',
  'getTavernHelperExtensionId',
  'getTavernHelperVersion',
  'getTavernRegexes',
  'getTavernVersion',
  'getVariables',
  'getWorldbook',
  'getWorldbookNames',
  'iframe_events',
  'importRawCharacter',
  'importRawChat',
  'importRawPreset',
  'importRawTavernRegex',
  'importRawWorldbook',
  'initializeGlobal',
  'injectPrompts',
  'insertOrAssignVariables',
  'insertVariables',
  'installExtension',
  'isAdmin',
  'isCharacterTavernRegexesEnabled',
  'isInstalledExtension',
  'isPresetNormalPrompt',
  'isPresetPlaceholderPrompt',
  'isPresetSystemPrompt',
  'loadPreset',
  'pauseAudio',
  'placeholder_prompt_default_order',
  'playAudio',
  'rebindCharWorldbooks',
  'rebindChatWorldbook',
  'rebindGlobalWorldbooks',
  'refreshOneMessage',
  'registerMacroLike',
  'registerVariableSchema',
  'reinstallExtension',
  'reloadIframe',
  'renamePreset',
  'replaceAudioList',
  'replaceCharacter',
  'replaceLorebookEntries',
  'replacePersona',
  'replacePreset',
  'replaceScriptButtons',
  'replaceScriptInfo',
  'replaceScriptTrees',
  'replaceTavernRegexes',
  'replaceVariables',
  'replaceWorldbook',
  'retrieveDisplayedMessage',
  'rotateChatMessages',
  'setAudioSettings',
  'setChatLorebook',
  'setChatMessages',
  'setCurrentCharLorebooks',
  'setLorebookEntries',
  'setLorebookSettings',
  'setPreset',
  'stopAllGeneration',
  'stopGenerationById',
  'substitudeMacros',
  'tavern_events',
  'triggerSlash',
  'uninjectPrompts',
  'uninstallExtension',
  'unregisterMacroLike',
  'updateCharacterWith',
  'updateExtension',
  'updateLorebookEntriesWith',
  'updatePersonaWith',
  'updatePresetWith',
  'updateScriptButtonsWith',
  'updateScriptTreesWith',
  'updateTavernRegexesWith',
  'updateVariablesWith',
  'updateWorldbookWith',
  'waitGlobalInitialized',
]
