/**
 * The card-facing consumption channel's payload: a small, generated client
 * bundle that the host materialises at `<plugin-assets>/<extensionId>/client.js`
 * when an ST extension activates, so the aggregated `/plugins/manifest.json`
 * gains a row and card frames load it through the existing
 * `data-iris-plugin` tag mechanism.
 *
 * Two contracts pin the call shape. The merge protocol: `registerPluginMembers`
 * lives on the core member table (`__iris_members__`), and the frame refuses a
 * registration whose plugin id is not admitted by the frame's snapshot — so a
 * stale cached bundle registers nothing, by landing-site-3 rule. The asset
 * scanner (`scanPluginMemberNames`) reads the bundle's source for
 * `registerPluginMembers("<literal id>", { <literal keys> })` — the id and the
 * member keys must stay string/identifier literals or the PluginCenter's
 * member status goes blind to this bundle.
 *
 * The bundle registers one member — `EjsTemplate`, a proxy onto the
 * extension's own published API. The proxy is thin by design: it posts a
 * `member-call` envelope to its parent (the shell, which hosts the extension
 * plane), and the plane forwards it into the extension frame where the REAL
 * `globalThis.EjsTemplate` answers. No upstream code runs in the card frame;
 * no card code runs in the extension frame; every call crosses both edges
 * through the tokened channel.
 *
 * This string is the artifact of record — the file the host writes is this
 * bundle verbatim, so a test can assert the served bytes register under the
 * plugin id they claim.
 */

export const ST_COMPAT_MEMBER_METHODS = [
  'evalTemplate',
  'evalTemplateWI',
  'setVariable',
  'getVariable',
] as const

export function buildMemberBundle(extensionId: string): string {
  if (!/^[A-Za-z0-9_-]{1,64}$/u.test(extensionId)) {
    throw new TypeError(`member bundle: extension id "${extensionId}" is not a safe bundle identifier`)
  }
  const methods = ST_COMPAT_MEMBER_METHODS.map(method => `'${method}'`).join(', ')
  return `/* Generated by @iris/compat-st-extension — the ST-compat pilot's card-facing member proxy.
 * Source of record: packages/iris-compat-st-extension/src/host/member-bundle.ts (buildMemberBundle).
 * Do not edit the served copy; regenerate instead. */
(function () {
  'use strict';
  var PLUGIN_ID = '${extensionId}';
  var METHODS = [${methods}];
  var seq = 0;
  var pending = new Map();

  function call(method, args) {
    return new Promise(function (resolve, reject) {
      seq += 1;
      var callId = PLUGIN_ID + ':' + String(seq);
      pending.set(callId, { resolve: resolve, reject: reject });
      window.parent.postMessage({ irisStMemberProxy: PLUGIN_ID, irisStMemberResult: 'st-compat', callId: callId, method: method, args: args }, '*');
      setTimeout(function () {
        if (pending.has(callId)) {
          pending.delete(callId);
          reject(new Error('EjsTemplate.' + method + ' timed out (the extension plane did not answer)'));
        }
      }, 8000);
    });
  }

  window.addEventListener('message', function (event) {
    if (event.source !== window.parent) return;
    var data = event.data;
    if (typeof data !== 'object' || data === null) return;
    if (data['irisStMemberResult'] !== 'st-compat' || typeof data['callId'] !== 'string') return;
    var entry = pending.get(data['callId']);
    if (!entry) return;
    pending.delete(data['callId']);
    if (typeof data['error'] === 'string') entry.reject(new Error(data['error']));
    else entry.resolve(data['result']);
  });

  var proxy = {};
  METHODS.forEach(function (method) {
    proxy[method] = function () { return call(method, Array.prototype.slice.call(arguments)); };
  });

  var members = globalThis['__iris_members__'];
  members.registerPluginMembers('${extensionId}', { EjsTemplate: Object.freeze(proxy) });
})();
`
}
